// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"amartha/src/controllers/hello"
	"amartha/src/utils/echo"
	"amartha/src/utils/server"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func Initialize() (*server.Server, func(), error) {
	echoEcho := echo.NewEcho()
	helloController := hello_controller.NewHelloController()
	controllers := &server.Controllers{
		HelloController: helloController,
	}
	serverServer := server.NewServer(echoEcho, controllers)
	return serverServer, func() {
	}, nil
}
