// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"amartha/src/loans/controller"
	"amartha/src/utils/config"
	"amartha/src/utils/echo"
	"amartha/src/utils/server"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func Initialize() (*server.Server, func(), error) {
	echoEcho := echo.NewEcho()
	loanController := controller.NewLoanController()
	controllers := &server.Controllers{
		LoanController: loanController,
	}
	configConfig := config.LoadConfig()
	serverServer := server.NewServer(echoEcho, controllers, configConfig)
	return serverServer, func() {
	}, nil
}
