// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	controller2 "amartha/src/account/controller"
	service2 "amartha/src/account/service"
	"amartha/src/loan/controller"
	"amartha/src/loan/service"
	"amartha/src/utils/config"
	"amartha/src/utils/database"
	"amartha/src/utils/echo"
	"amartha/src/utils/echo/middleware"
	"amartha/src/utils/server"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func Initialize() (*server.Server, func(), error) {
	echoEcho := echo.NewEcho()
	configConfig := config.LoadConfig()
	db := database.NewDBConnection(configConfig)
	queries := database.NewQueries(db)
	loanService := service.NewLoanService(db, queries)
	authMiddleware := middleware.NewAuthMiddleware(queries)
	guardLoanService := service.NewGuardLoanService(queries)
	loanController := controller.NewLoanController(loanService, authMiddleware, guardLoanService)
	accountService := service2.NewAccountService(queries)
	accountController := controller2.NewAccountController(accountService)
	controllers := &server.Controllers{
		LoanController:    loanController,
		AccountController: accountController,
	}
	serverServer := server.NewServer(echoEcho, controllers, configConfig)
	return serverServer, func() {
	}, nil
}
